/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frm_view;

import dao.CadastroDAO;
import metodos.LoginMetodos;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author luizf
 */
public class FrmCadastro extends javax.swing.JFrame {

    /**
     * Creates new form FrmCadastro
     */
    public FrmCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        emailCadastro = new javax.swing.JTextField();
        usuarioCadastro = new javax.swing.JTextField();
        btnCadastro = new javax.swing.JButton();
        senhaCadastro = new javax.swing.JPasswordField();
        nomeCadastro = new javax.swing.JTextField();
        btnVoltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 538));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        emailCadastro.setBackground(new java.awt.Color(255, 255, 255));
        emailCadastro.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        emailCadastro.setForeground(new java.awt.Color(153, 153, 153));
        emailCadastro.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(emailCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 200, 234, -1));

        usuarioCadastro.setBackground(new java.awt.Color(255, 255, 255));
        usuarioCadastro.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        usuarioCadastro.setForeground(new java.awt.Color(153, 153, 153));
        usuarioCadastro.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(usuarioCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, 234, -1));

        btnCadastro.setBackground(new java.awt.Color(255, 255, 255));
        btnCadastro.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnCadastro.setForeground(new java.awt.Color(0, 0, 0));
        btnCadastro.setText("CADASTRE-SE");
        btnCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 360, 120, 30));

        senhaCadastro.setBackground(new java.awt.Color(255, 255, 255));
        senhaCadastro.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        senhaCadastro.setForeground(new java.awt.Color(153, 153, 153));
        senhaCadastro.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(senhaCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, 230, 30));

        nomeCadastro.setBackground(new java.awt.Color(255, 255, 255));
        nomeCadastro.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        nomeCadastro.setForeground(new java.awt.Color(153, 153, 153));
        nomeCadastro.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(nomeCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, 234, -1));

        btnVoltar.setBackground(new java.awt.Color(255, 255, 255));
        btnVoltar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(0, 0, 0));
        btnVoltar.setText("VOLTAR");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, 90, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/LisTudo - CADASTRO.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-500, 0, 1410, 560));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método Button "Cadastra-se", no qual o mesmo for pressionado.
     */
    private void btnCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroActionPerformed

        FrmViewLogin viewLogin = new FrmViewLogin();

        LoginMetodos loginMetodos = new LoginMetodos();

        /**
         * Armazena todos as veriaveis (nome, email, nomeUsuario, senha).
         */
        loginMetodos.setNome(nomeCadastro.getText());
        loginMetodos.setEmail(emailCadastro.getText());
        loginMetodos.setNomeUsuario(usuarioCadastro.getText());
        loginMetodos.setSenha(senhaCadastro.getText());

        CadastroDAO cadastro = new CadastroDAO();

        try {

            String resultadoCadastro = cadastro.cadastrarUsuario(loginMetodos); //IRÁ VALIDAR SE JÁ EXISTE USUARIO OU EMAIL CADASTRADOS

            switch (resultadoCadastro) {

                case "USUARIO EXISTENTE":

                    JOptionPane.showMessageDialog(null, "USUARIO JÁ CADASTRADO!");
                    break;

                case "EMAIL EXISTENTE":

                    JOptionPane.showMessageDialog(null, "EMAIL JÁ CADASTRADO!");
                    break;

                case "USUARIO E EMAIL EXISTENTE":

                    JOptionPane.showMessageDialog(null, "USUARIO E EMAIL JÁ CADASTRADO!");
                    break;

                case "VALOR NULO":

                    JOptionPane.showMessageDialog(null, "POR FAVOR, PREENCHA TODOS OS CAMPOS!");
                    break;

                default:

                    JOptionPane.showMessageDialog(null, "CADASTRO REALIZADO COM SUCESSO!!!");
                    new FrmViewLogin().setVisible(true);
                    this.dispose();
                    break;

            }

        } catch (SQLException ex) {

            Logger.getLogger(FrmCadastro.class.getName()).log(Level.SEVERE, null, ex);

        }

    }//GEN-LAST:event_btnCadastroActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed

        new FrmViewLogin().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastro;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JTextField emailCadastro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nomeCadastro;
    private javax.swing.JPasswordField senhaCadastro;
    private javax.swing.JTextField usuarioCadastro;
    // End of variables declaration//GEN-END:variables
}
